spring:
  datasource:
    url: jdbc:mysql://localhost:3306/management?allowMultiQueries=true&autoReconnect=true&&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: management-backend
