spring:
  datasource:
    url: jdbc:mysql://localhost:3306/management?useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    show-sql: true
  application:
    name: management-backend
